name: pdfreader
description: "PDF Reader"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/build/
    # Web Ana Dosyalar
    - assets/web/
    - assets/web/birlestirme.html
    - assets/web/index.html
    - assets/web/lang.js
    - assets/web/pdf-lib.min.js
    - assets/web/viewer.html
    - assets/web/viewer.css
    - assets/web/viewer.mjs
    
    # Fontlar ve Görseller
    - assets/web/fonts/
    - assets/web/fonts/MaterialSymbolsRounded.woff2
    - assets/web/images/
    
    # Locale Klasörleri (viewer.ftl dosyalarını içermektedir)
    - assets/web/locale/
    - assets/web/locale/af/
    - assets/web/locale/ar/
    - assets/web/locale/ast/
    - assets/web/locale/az/
    - assets/web/locale/be/
    - assets/web/locale/bg/
    - assets/web/locale/bn/
    - assets/web/locale/br/
    - assets/web/locale/bs/
    - assets/web/locale/ca/
    - assets/web/locale/cak/
    - assets/web/locale/cs/
    - assets/web/locale/cy/
    - assets/web/locale/da/
    - assets/web/locale/de/
    - assets/web/locale/el/
    - assets/web/locale/en-CA/
    - assets/web/locale/en-GB/
    - assets/web/locale/en-US/
    - assets/web/locale/eo/
    - assets/web/locale/es-AR/
    - assets/web/locale/es-CL/
    - assets/web/locale/es-ES/
    - assets/web/locale/es-MX/
    - assets/web/locale/et/
    - assets/web/locale/eu/
    - assets/web/locale/fa/
    - assets/web/locale/ff/
    - assets/web/locale/fi/
    - assets/web/locale/fr/
    - assets/web/locale/fur/
    - assets/web/locale/fy-NL/
    - assets/web/locale/ga-IE/
    - assets/web/locale/gd/
    - assets/web/locale/gl/
    - assets/web/locale/gu-IN/
    - assets/web/locale/he/
    - assets/web/locale/hi-IN/
    - assets/web/locale/hr/
    - assets/web/locale/hu/
    - assets/web/locale/hy-AM/
    - assets/web/locale/ia/
    - assets/web/locale/id/
    - assets/web/locale/is/
    - assets/web/locale/it/
    - assets/web/locale/ja/
    - assets/web/locale/ka/
    - assets/web/locale/kab/
    - assets/web/locale/kk/
    - assets/web/locale/km/
    - assets/web/locale/kn/
    - assets/web/locale/ko/
    - assets/web/locale/lo/
    - assets/web/locale/lt/
    - assets/web/locale/lv/
    - assets/web/locale/meh/
    - assets/web/locale/mk/
    - assets/web/locale/ml/
    - assets/web/locale/ms/
    - assets/web/locale/my/
    - assets/web/locale/nb-NO/
    - assets/web/locale/ne-NP/
    - assets/web/locale/nl/
    - assets/web/locale/nn-NO/
    - assets/web/locale/oc/
    - assets/web/locale/pa-IN/
    - assets/web/locale/pl/
    - assets/web/locale/pt-BR/
    - assets/web/locale/pt-PT/
    - assets/web/locale/rm/
    - assets/web/locale/ro/
    - assets/web/locale/ru/
    - assets/web/locale/sat/
    - assets/web/locale/sc/
    - assets/web/locale/scn/
    - assets/web/locale/sk/
    - assets/web/locale/sl/
    - assets/web/locale/son/
    - assets/web/locale/sq/
    - assets/web/locale/sr/
    - assets/web/locale/sv-SE/
    - assets/web/locale/szl/
    - assets/web/locale/ta/
    - assets/web/locale/te/
    - assets/web/locale/tg/
    - assets/web/locale/th/
    - assets/web/locale/tl/
    - assets/web/locale/tr/
    - assets/web/locale/trs/
    - assets/web/locale/uk/
    - assets/web/locale/ur/
    - assets/web/locale/uz/
    - assets/web/locale/vi/
    - assets/web/locale/wo/
    - assets/web/locale/xh/
    - assets/web/locale/zh-CN/
    - assets/web/locale/zh-TW/
